# Self-Hosted Github Action Runners on GCP via Cirun.io
# Reference: https://docs.cirun.io/Reference/yml.html
runners:
  - name: "gpu-e2e-runner"
    # Cloud Provider: GCP
    cloud: "gcp"
    # Cheapest GPU on GCP
    gpu: "nvidia-tesla-t4"
    instance_type: "n1-standard-2"
    # Ubuntu-20.4, can be seen from "gcloud compute images list"
    machine_image: "ubuntu-2004-focal-v20221018"
    preemptible: true
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-gpu-e2e-runner"
